# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release package

on:
  workflow_run:
    workflows: ["Semantic Release"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Build and publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TWINE_API_TOKEN }}
        run: |
          uv build
          uv publish
